name: "JS SDK Checks"

on:
  push:
    branches:
      - main
    paths:
      - "signer/**"
      - "protos/**"
      - "sdks/js/**"
      - ".github/workflows/js-sdk.yml"
  pull_request:
    paths:
      - "signer/**"
      - "protos/**"
      - "sdks/js/**"
      - ".github/workflows/js-sdk.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "22.x"]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run JS SDK unit tests"
        uses: ./public/actions/js-sdk-unit-test
        with:
          node-version: ${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
